const artistConstants = {
    GET_ARTIST_REQUEST: 'GET_ARTIST_REQUEST',
    GET_ARTIST_SUCCESS: 'GET_ARTIST_SUCCESS',
    GET_ARTIST_FAILURE: 'GET_ARTIST_FAILURE',

    GET_ARTIST_ALBUM_REQUEST: 'GET_ARTIST_ALBUM_REQUEST',
    GET_ARTIST_ALBUM_SUCCESS: 'GET_ARTIST_ALBUM_SUCCESS',
    GET_ARTIST_ALBUM_FAILURE: 'GET_ARTIST_ALBUM_FAILURE',
};

export default artistConstants;
