const playlistConstants = {
    GET_ALL_MY_USER_PLAYLISTS_REQUEST: 'GET_ALL_MY_USER_PLAYLISTS_REQUEST',
    GET_ALL_MY_USER_PLAYLISTS_SUCCESS: 'GET_ALL_MY_USER_PLAYLISTS_SUCCESS',
    GET_ALL_MY_USER_PLAYLISTS_FAILURE: 'GET_ALL_MY_USER_PLAYLISTS_FAILURE',

    GET_PLAYLIST_REQUEST: 'GET_PLAYLIST_REQUEST',
    GET_PLAYLIST_SUCCESS: 'GET_PLAYLIST_SUCCESS',
    GET_PLAYLIST_FAILURE: 'GET_PLAYLIST_FAILURE',
}

export default playlistConstants;
