const searchConstants = {
    SEARCH_ALBUM_REQUEST: 'SEARCH_ALBUM_REQUEST',
    SEARCH_ALBUM_SUCCESS: 'SEARCH_ALBUM_SUCCESS',
    SEARCH_ALBUM_FAILURE: 'SEARCH_ALBUM_FAILURE',

    SEARCH_ARTIST_REQUEST: 'SEARCH_ARTIST_REQUEST',
    SEARCH_ARTIST_SUCCESS: 'SEARCH_ARTIST_SUCCESS',
    SEARCH_ARTIST_FAILURE: 'SEARCH_ARTIST_FAILURE',

    SEARCH_PLAYLIST_REQUEST: 'SEARCH_PLAYLIST_REQUEST',
    SEARCH_PLAYLIST_SUCCESS: 'SEARCH_PLAYLIST_SUCCESS',
    SEARCH_PLAYLIST_FAILURE: 'SEARCH_PLAYLIST_FAILURE',

    SEARCH_TRACK_REQUEST: 'SEARCH_ALBUM_REQUEST',
    SEARCH_TRACK_SUCCESS: 'SEARCH_ALBUM_SUCCESS',
    SEARCH_TRACK_FAILURE: 'SEARCH_ALBUM_FAILURE',
};

export default searchConstants;
