const tokensConstants = {
    GET_AUTHORIZATION_CODE_REQUEST: 'GET_AUTHORIZATION_CODE_REQUEST',
    GET_AUTHORIZATION_CODE_SUCCESS: 'GET_AUTHORIZATION_CODE_SUCCESS',
    GET_AUTHORIZATION_CODE_FAILURE: 'GET_AUTHORIZATION_CODE_FAILURE',
}

export default tokensConstants;
