const tokensConstants = {
    GET_AUTHORIZATION_CODE_REQUEST: 'GET_AUTHORIZATION_CODE_REQUEST',
    GET_AUTHORIZATION_CODE_SUCCESS: 'GET_AUTHORIZATION_CODE_SUCCESS',
    GET_AUTHORIZATION_CODE_FAILURE: 'GET_AUTHORIZATION_CODE_FAILURE',
    GET_ACCESS_TOKEN_REQUEST: 'GET_ACCESS_TOKEN_REQUEST',
    GET_ACCESS_TOKEN_SUCCESS: 'GET_ACCESS_TOKEN_SUCCESS',
    GET_ACCESS_TOKEN_FAILURE: 'GET_ACCESS_TOKEN_FAILURE',
}

export default tokensConstants;
