const userConstants = {
    GET_MY_USER_REQUEST: 'GET_MY_USER_REQUEST',
    GET_MY_USER_SUCCESS: 'GET_MY_USER_SUCCESS',
    GET_MY_USER_FAILURE: 'GET_MY_USER_FAILURE',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    GET_TOP_ARTISTS_REQUEST: 'GET_TOP_ARTISTS_REQUEST',
    GET_TOP_ARTISTS_SUCCESS: 'GET_TOP_ARTISTS_SUCCESS',
    GET_TOP_ARTISTS_FAILURE: 'GET_TOP_ARTISTS_FAILURE',

    GET_TOP_TRACKS_REQUEST: 'GET_TOP_TRACKS_REQUEST',
    GET_TOP_TRACKS_SUCCESS: 'GET_TOP_TRACKS_SUCCESS',
    GET_TOP_TRACKS_FAILURE: 'GET_TOP_TRACKS_FAILURE',
};

export default userConstants;
