const userConstants = {
    GET_MY_USER_REQUEST: 'GET_MY_USER_REQUEST',
    GET_MY_USER_SUCCESS: 'GET_MY_USER_SUCCESS',
    GET_MY_USER_FAILURE: 'GET_MY_USER_FAILURE',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    GET_TOP_REQUEST: 'GET_TOP_REQUEST',
    GET_TOP_SUCCESS: 'GET_TOP_SUCCESS',
    GET_TOP_FAILURE: 'GET_TOP_FAILURE',

};

export default userConstants;
